name: Publish a bot
description: Submit your bot to be automatically validated and published on the store.
title: "bot: {name}"
body:
  - type: input
    id: description
    attributes:
      label: description
      description: 描述
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: author
      description: 作者
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: homepage
      description: 主页
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: tags
      description: 标签，以 `,` 分割，如 `tag1,tag2`
    validations:
      required: true
