name: Publish a plugin
description: Submit your plugin to be automatically validated and published on the store.
title: "[plugin]: {name}"
body:
  - type: input
    id: pypi_name
    attributes:
      label: pypi_name
      description: PyPI 项目名
    validations:
      required: true

  - type: input
    id: module_name
    attributes:
      label: module_name
      description: import 时的包名
    validations:
      required: true
