name: Deploy JSON Files

on:
  push:
    branches:
      - "main"
    paths:
      - "bots.json"
      - "adapters.json"
      - "plugins.json"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create public directory
        run: mkdir public

      - name: Compress JSON files with jq
        run: |
          jq --compact-output . bots.json > public/bots.json
          jq --compact-output . adapters.json > public/adapters.json
          jq --compact-output . plugins.json > public/plugins.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
