name: Update Store Data

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  validation:
    if: github.event_name == 'issues' || (github.event_name == 'issue_comment' && github.event.issue.state == 'open' && github.event.comment.body == '/validate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh
      - name: Run Python script
        run: uv run script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
