name: Update Store Data

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  validation:
    if: github.event_name == 'issues' || (github.event_name == 'issue_comment' && github.event.issue.state == 'open' && github.event.comment.body == '/validate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: "3.10"
          cache: true
      - name: Install dependencies
        run: pdm install --prod
      - name: Run Python script
        run: pdm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
